clc; clear; close all;

digitDatasetPath = fullfile('C:\','Users','Tyler', '.cache', ...
    'kagglehub', 'datasets', 'preatcher', 'standard-ocr-dataset', ...
    'versions', '2', 'data', 'training_data'); 

imds = imageDatastore(digitDatasetPath, ...
    IncludeSubfolders=true, ...
    LabelSource="foldernames");

options = trainingOptions("sgdm", ...
    InitialLearnRate=0.01, ...
    MaxEpochs=4, ...
    Shuffle="every-epoch", ...
    ValidationData=imds, ...
    ValidationFrequency=30, ...
    Plots="training-progress", ...
    Metrics="accuracy", ...
    Verbose=false);

detector = yolov4ObjectDetector("tiny-yolov4-coco");

images = imds.Files;

detector = trainYOLOv4ObjectDetector(imds,detector,options);